# Generated by Django 4.0.4 on 2022-04-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user management', 'verbose_name_plural': 'users management'},
        ),
    ]
