# Generated by Django 4.0.4 on 2022-04-27 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('short_description', models.CharField(max_length=400, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='article')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('slug', models.SlugField(max_length=400, unique=True, verbose_name='url slug')),
                ('is_active', models.BooleanField(verbose_name='is active ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
