# Generated by Django 4.0.4 on 2022-04-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='url slug')),
                ('is_active', models.BooleanField(verbose_name='is active ?')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article.articlecategory', verbose_name='category'),
        ),
    ]
