# Generated by Django 4.0.4 on 2022-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='confirmed ?'),
        ),
    ]
