# Generated by Django 4.0.4 on 2022-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='site name')),
                ('site_url', models.URLField(max_length=300, verbose_name='site url')),
                ('site_logo', models.ImageField(upload_to='logo/', verbose_name=' site logo')),
                ('about_us', models.CharField(max_length=400, verbose_name='about us')),
                ('email', models.EmailField(max_length=254, verbose_name='site email')),
                ('phone_number', models.CharField(max_length=100, verbose_name='mobile number')),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
