# Generated by Django 4.0.4 on 2022-04-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_remove_headerlink_link_headerlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active ?'),
            preserve_default=False,
        ),
    ]
