# Generated by Django 4.0.4 on 2022-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_sitesetting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name=' site logo'),
        ),
    ]
