# Generated by Django 4.0.4 on 2022-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(max_length=300, verbose_name='title')),
                ('intro_tag', models.CharField(max_length=300, verbose_name='tag')),
                ('intro_description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intro,s',
            },
        ),
    ]
