# Generated by Django 4.0.4 on 2022-04-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0007_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='intro_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='intro_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='intro_title',
            new_name='title',
        ),
    ]
