# Generated by Django 4.0.4 on 2022-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0008_rename_intro_description_intro_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active ?'),
            preserve_default=False,
        ),
    ]
